// Mocks generated by Mockito 5.4.4 from annotations
// in fudo_interview/test/presentation/post_list_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:fudo_interview/src/api/post_api.dart' as _i3;
import 'package:fudo_interview/src/api/user_api.dart' as _i5;
import 'package:fudo_interview/src/models/post/post.dart' as _i2;
import 'package:fudo_interview/src/models/user/user.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakePost_0 extends _i1.SmartFake implements _i2.Post {
  _FakePost_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [PostApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockPostApi extends _i1.Mock implements _i3.PostApi {
  @override
  _i4.Future<List<_i2.Post>> getPosts() => (super.noSuchMethod(
        Invocation.method(
          #getPosts,
          [],
        ),
        returnValue: _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i2.Post>>.value(<_i2.Post>[]),
      ) as _i4.Future<List<_i2.Post>>);

  @override
  _i4.Future<_i2.Post> getPost(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getPost,
          [id],
        ),
        returnValue: _i4.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #getPost,
            [id],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #getPost,
            [id],
          ),
        )),
      ) as _i4.Future<_i2.Post>);

  @override
  _i4.Future<_i2.Post> createPost(_i2.Post? post) => (super.noSuchMethod(
        Invocation.method(
          #createPost,
          [post],
        ),
        returnValue: _i4.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #createPost,
            [post],
          ),
        )),
        returnValueForMissingStub: _i4.Future<_i2.Post>.value(_FakePost_0(
          this,
          Invocation.method(
            #createPost,
            [post],
          ),
        )),
      ) as _i4.Future<_i2.Post>);
}

/// A class which mocks [UserApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserApi extends _i1.Mock implements _i5.UserApi {
  @override
  _i4.Future<List<_i6.User>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i4.Future<List<_i6.User>>);

  @override
  _i4.Future<List<_i6.User>> getUsersByName(String? name) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUsersByName,
          [name],
        ),
        returnValue: _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
        returnValueForMissingStub:
            _i4.Future<List<_i6.User>>.value(<_i6.User>[]),
      ) as _i4.Future<List<_i6.User>>);
}
